#!/usr/bin/env node
/* ==========================================================================
   Build step: encrypt every protected case-study section.

   Reads  : *.source.html        (one per section, e.g. ai-test-studio.source.html)
   Writes : protect-content.js    (window.ProtectedPayloads = { "<id>": {...} })

   The section id is the file name without ".source.html"
   (ai-test-studio.source.html  ->  id "ai-test-studio").

   Usage:
       node encrypt-content.cjs "SHARED-PASSWORD"
     or
       PROTECT_PASSWORD="SHARED-PASSWORD" node encrypt-content.cjs

   All sections are encrypted with the SAME password (shared password), each
   with its own random salt + IV. The password is never stored. Wrong password
   => GCM auth fails => nothing is revealed.
   ========================================================================== */
const fs = require("fs");
const path = require("path");
const { webcrypto } = require("crypto");
const subtle = webcrypto.subtle;

const ITERATIONS = 150000;
const DIR = __dirname;
const OUT = path.join(DIR, "protect-content.js");

const password = process.argv[2] || process.env.PROTECT_PASSWORD;
if (!password) {
  console.error('Error: provide the shared password, e.g.  node encrypt-content.cjs "your-password"');
  process.exit(1);
}

const sources = fs.readdirSync(DIR).filter(function (f) { return f.endsWith(".source.html"); }).sort();
if (!sources.length) {
  console.error("Error: no *.source.html files found in " + DIR);
  process.exit(1);
}

const b64 = (buf) => Buffer.from(buf).toString("base64");

async function encryptOne(plaintext) {
  const enc = new TextEncoder();
  const salt = webcrypto.getRandomValues(new Uint8Array(16));
  const iv = webcrypto.getRandomValues(new Uint8Array(12));
  const baseKey = await subtle.importKey("raw", enc.encode(password), "PBKDF2", false, ["deriveKey"]);
  const key = await subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: ITERATIONS, hash: "SHA-256" },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt"]
  );
  const cipher = await subtle.encrypt({ name: "AES-GCM", iv }, key, enc.encode(plaintext));
  return { v: 1, iter: ITERATIONS, salt: b64(salt), iv: b64(iv), data: b64(new Uint8Array(cipher)) };
}

(async () => {
  const payloads = {};
  for (const file of sources) {
    const id = file.replace(/\.source\.html$/, "");
    const plaintext = fs.readFileSync(path.join(DIR, file), "utf8");
    payloads[id] = await encryptOne(plaintext);
    console.log("  encrypted " + id + " (" + Buffer.byteLength(plaintext, "utf8") + " bytes)");
  }

  const out =
    "/* AUTO-GENERATED by encrypt-content.cjs — do not edit by hand.\n" +
    "   AES-256-GCM ciphertext of each protected section, keyed by section id.\n" +
    "   Useless without the password. Regenerate with:\n" +
    '       node encrypt-content.cjs "SHARED-PASSWORD"  */\n' +
    "window.ProtectedPayloads = " + JSON.stringify(payloads) + ";\n";

  fs.writeFileSync(OUT, out);
  console.log("Wrote " + OUT + " (" + sources.length + " section(s))");
})().catch((e) => { console.error(e); process.exit(1); });
